Hw02 unpack string
Tsaplin/sts-go-repo pull request #2
Opened 2024-09-08 13:32 UTC by Tsaplin

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-10 19:46 UTC, vladislavmass approved these changes

2024-09-10 19:46 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +			resultStr += arr[i]
В го строки это не изменяемый тип данных, поэтому каждая конкатенация строк приводит к выделению памяти и копированию данных в эту новую область. Для решения данной проблемы рекомендуется использовать strings.Builder

2024-09-10 19:46 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +	arr := strings.Split(str, "")
В результат работы данного кода arr это слайс строк, хотя по факту должен быть массивом рун

2024-09-10 19:46 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +
Пустая строка тут явно лишняя

2024-09-11 14:07 UTC, Tsaplin commented on hw02_unpack_string/main.go
> +			resultStr += arr[i]
Подключил strings.Builder

2024-09-11 14:08 UTC, Tsaplin commented on hw02_unpack_string/main.go
> +
Убрал пустую строку

2024-09-11 14:09 UTC, Tsaplin commented on hw02_unpack_string/main.go
> +	arr := strings.Split(str, "")
Да, я именно с массивом строк дальше работаю. А чем это хуже, чем массив рун ?

2024-09-11 14:34 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +	arr := strings.Split(str, "")
Строка весит больше чем руна, а также строка это по сути указатель на некую область памяти и по итогу мы получаем двойную адресацию. Тоесть мы должны перейти по индексу в слайсе и после этого еще перейти по указателю. Руна же по сути это просто число. Вот и получается что мы хоть и не сильно но расходуем больше памяти и тратим больше тактов на операцию.  Зачем это делать , когда можно легко этого не делать

2024-09-11 16:11 UTC, hungry-honeybadger requested changes

2024-09-11 16:11 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +func RemoveChar(word string) (result string) {
Удаления таким образом не будет работать. Так как тут берется не срез символов а срез байт.  Для демонстрации проблемы можно использовать следующий тест кейс `{input: "qффwф0", expected: "qффw"},`

2024-09-11 19:35 UTC, Tsaplin commented on hw02_unpack_string/main.go
> +func RemoveChar(word string) (result string) {
Переделал метод удаления на руны

2024-09-12 04:51 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +func RemoveChar(word string) (result string) {
О каких ошибках идет речь?

2024-09-12 04:57 UTC, vladislavmass commented on hw02_unpack_string/main.go
> +func RemoveChar(word string) (result string) {
Те тесты это по сути тесты для задания со звездочкой. Они требуют отдельной реализации механизма экранирования.

2024-09-12 09:01 UTC, Tsaplin commented on hw02_unpack_string/main.go
> +func RemoveChar(word string) (result string) {
Понял, спасибо

2024-09-12 09:54 UTC, vladislavmass approved these changes

2024-09-12 11:09 UTC, merged