Hw03 frequency analysis
Tsaplin/sts-go-repo pull request #3
Opened 2024-09-22 20:07 UTC by Tsaplin

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-22 20:08 UTC, Tsaplin commented
Не могу понять, на что ругаются линтеры ((

2024-09-23 18:01 UTC, vladislavmass requested changes

2024-09-23 18:01 UTC, vladislavmass commented on hw03_frequency_analysis/main.go
> +	inputStr = strings.ReplaceAll(inputStr, "\n\t\t\t", " ")
Поясните пожалуйста зачем нужен весь этот код? Чем не устроил strings.Fields?

2024-09-23 19:38 UTC, Tsaplin commented on hw03_frequency_analysis/main.go
> +	inputStr = strings.ReplaceAll(inputStr, "\n\t\t\t", " ")
Спасибо, подключил. Получилось гораздо изящней.

2024-09-24 05:17 UTC, vladislavmass requested changes
Пока работу принять не могу, так как есть критическая ошибка. В целом алгоритм выглядет странным подсчет числа слов за квадратичное сложность, в место линиейной через использованием мапы

2024-09-24 05:17 UTC, vladislavmass commented on hw03_frequency_analysis/main.go
> +	topWordFreqArray := wordFreqArray[0:resultLength]
Сначала резать, потом сортировать это не рабочий вариант. Так как можно отрезать то, что должно быть впереди. Для проверки попробуйте следующий тест кейс. `"x z y m n v b l k o p a c"`

2024-09-24 06:27 UTC, Tsaplin commented on hw03_frequency_analysis/main.go
> +	topWordFreqArray := wordFreqArray[0:resultLength]
Спасибо, внес исправление.

2024-09-24 11:50 UTC, vladislavmass approved these changes

2024-09-24 12:43 UTC, merged