Hw04 lru cache
Tsaplin/sts-go-repo pull request #4
Opened 2024-09-29 15:10 UTC by Tsaplin

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-09-29 16:02 UTC, vladislavmass requested changes

2024-09-29 16:02 UTC, hungry-honeybadger commented on hw04_lru_cache/main.go
> +		if t.queue.Len()+1 > t.capacity {
Зачем использовать сложение, если есть больше или равно?

2024-09-29 16:02 UTC, hungry-honeybadger commented on hw04_lru_cache/main.go
> +			for k, v := range t.items {
Итерирование по items выполняется за линейное время, а код должен работать за O(1)

2024-09-29 16:02 UTC, hungry-honeybadger commented on hw04_lru_cache/main.go
> +	clear(t.items)
Мы очистили мапу но информация осталась в списке.

2024-09-29 16:02 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if t.length > 0 {
Эта проверка не нужна. Если t.head нет то и так вернется nil

2024-09-29 16:02 UTC, hungry-honeybadger commented on hw04_lru_cache/list.go
> +	if t.length != 0 {
Эта проверка не нужна. Если t.tail нет то и так вернется nil

2024-09-29 16:02 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	var newItem = ListItem{nil, nil, nil}
Лучше было бы сделать инициализацию полей сразу и через именованные поля.

2024-09-29 19:56 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +		if t.queue.Len()+1 > t.capacity {
Переделал на >=

2024-09-29 19:56 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +	clear(t.items)
Добавил очистку списка через создание нового

2024-09-29 19:56 UTC, Tsaplin commented on hw04_lru_cache/list.go
> +	if t.length > 0 {
Убрал

2024-09-29 19:56 UTC, Tsaplin commented on hw04_lru_cache/list.go
> +	if t.length != 0 {
Убрал

2024-09-29 19:56 UTC, Tsaplin commented on hw04_lru_cache/list.go
> +	var newItem = ListItem{nil, nil, nil}
Сделал

2024-09-30 20:41 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +			for k, v := range t.items {
Изменил реализацию: в списке сохраняю теперь не только значения, но и ключи. Благодаря этому удалось тут реализовать удаление по ключу.

2024-10-02 04:38 UTC, vladislavmass requested changes

2024-10-02 04:38 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +func (t *myList) Remove(i *ListItem) {
В этом методе за место 4 ifов можно сделать 2 if else. Так как ряд условий взаимоисключающие

2024-10-02 04:38 UTC, vladislavmass commented on hw04_lru_cache/main.go
> +			for k := range tailValue.(map[Key]interface{}) {
Range в любом случае работает за линейное время.  Поэтому опять таки мы имеем O(n) за место 0(1)

2024-10-02 04:38 UTC, vladislavmass commented on hw04_lru_cache/main.go
> +		tempMap := make(map[Key]interface{})
Непонятно зачем тут использовать папу за место структуры с 2 полями

2024-10-02 07:34 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +			for k := range tailValue.(map[Key]interface{}) {
Но ведь внутри цикла for мы сейчас проходим лишь по одному элементу ? Может можно как-то иначе получить ключ из tailValue... Но я не нашел способа.

2024-10-02 07:35 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +		tempMap := make(map[Key]interface{})
А чем хуже мапа ?

2024-10-02 13:56 UTC, vladislavmass commented on hw04_lru_cache/main.go
> +			for k := range tailValue.(map[Key]interface{}) {
То, что длинна лапы сейчас равна 1 не меняет того что алгоритмическая сложность итерации по маме это O(n) а не O(1). Если в tailValue будет структура из 2 полей, то можно просто обратится к полю в котором лежит Key эта операция работает за O(1)

2024-10-02 13:57 UTC, hungry-honeybadger commented on hw04_lru_cache/main.go
> +		tempMap := make(map[Key]interface{})
Тем что из за нее приходится юзать range и это не дает сдать данную работу

2024-10-02 18:38 UTC, Tsaplin commented on hw04_lru_cache/list.go
> +func (t *myList) Remove(i *ListItem) {
Заменил

2024-10-02 18:57 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +		tempMap := make(map[Key]interface{})
Заменил мапу структурой dataStruct

2024-10-02 18:57 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +			for k := range tailValue.(map[Key]interface{}) {
Заменил мапу структурой dataStruct.

2024-10-04 04:24 UTC, vladislavmass requested changes

2024-10-04 04:24 UTC, vladislavmass commented on hw04_lru_cache/main.go
> +	t.queue.PushFront(dynamicValue)
Тут должен быть MoveToFront, а не PushFront.

2024-10-04 08:02 UTC, Tsaplin commented on hw04_lru_cache/main.go
> +	t.queue.PushFront(dynamicValue)
Исправил

2024-10-04 08:23 UTC, vladislavmass approved these changes

2024-10-04 09:46 UTC, merged